# Generated by Django 5.2.6 on 2025-10-08 23:30

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='funcionarios',
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='funcionarios',
            old_name='remunarecao',
            new_name='remuneracao',
        ),
        migrations.RenameField(
            model_name='funcionarios',
            old_name='tempoServico',
            new_name='tempo_de_servico',
        ),
    ]
