# Generated by Django 4.2.25 on 2025-11-05 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_alter_funcionarios_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='funcionarios',
            managers=[
            ],
        ),
    ]
