# Generated by Django 5.2.5 on 2025-11-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_alter_funcionarios_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionarios',
            name='remuneracao',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
